<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>Ssit.CrossX2.Framework.Games</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ssit.CrossX2\Ssit.CrossX2.csproj" />
    </ItemGroup>

</Project>
