<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-android;net10.0-ios</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="ppy.SDL3-CS" Version="2026.722.0"/>
        <PackageReference Include="ppy.SDL3_image-CS" Version="2026.722.0"/>
        <PackageReference Include="ppy.SDL3_mixer-CS" Version="2026.722.0"/>
        <PackageReference Include="SkiaSharp" Version="3.119.1"/>
        <PackageReference Include="NVorbis" Version="0.10.5" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Metal\Color.frag.metal">
        <LogicalName>Pipelines.Shaders.Color.frag.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Metal\Color.vert.metal">
        <LogicalName>Pipelines.Shaders.Color.vert.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Metal\Texture.frag.metal">
        <LogicalName>Pipelines.Shaders.Texture.frag.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Metal\Texture.vert.metal">
        <LogicalName>Pipelines.Shaders.Texture.vert.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Metal\TextureLight.frag.metal">
        <LogicalName>Pipelines.Shaders.TextureLight.frag.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Metal\TextureLight.vert.metal">
        <LogicalName>Pipelines.Shaders.TextureLight.vert.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Metal\ColorLight.frag.metal">
        <LogicalName>Pipelines.Shaders.ColorLight.frag.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Metal\ColorLight.vert.metal">
        <LogicalName>Pipelines.Shaders.ColorLight.vert.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Hlsl\Color.frag.hlsl">
        <LogicalName>Pipelines.Shaders.Color.frag.hlsl</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Hlsl\Color.vert.hlsl">
        <LogicalName>Pipelines.Shaders.Color.vert.hlsl</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Hlsl\Texture.frag.hlsl">
        <LogicalName>Pipelines.Shaders.Texture.frag.hlsl</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Hlsl\Texture.vert.hlsl">
        <LogicalName>Pipelines.Shaders.Texture.vert.hlsl</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Hlsl\TextureLight.frag.hlsl">
        <LogicalName>Pipelines.Shaders.TextureLight.frag.hlsl</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Hlsl\TextureLight.vert.hlsl">
        <LogicalName>Pipelines.Shaders.TextureLight.vert.hlsl</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Hlsl\ColorLight.frag.hlsl">
        <LogicalName>Pipelines.Shaders.ColorLight.frag.hlsl</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Pipelines\Shaders\Hlsl\ColorLight.vert.hlsl">
        <LogicalName>Pipelines.Shaders.ColorLight.vert.hlsl</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Shaders\Blur.frag.metal">
        <LogicalName>Shaders.Blur.frag.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Shaders\Crt.frag.metal">
        <LogicalName>Shaders.Crt.frag.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Shaders\Crt.vert.metal">
        <LogicalName>Shaders.Crt.vert.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Shaders\FullscreenQuad.vert.metal">
        <LogicalName>Shaders.FullscreenQuad.vert.metal</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="_Sdl3Impl\Graphics\Shaders\GlowComposite.frag.metal">
        <LogicalName>Shaders.GlowComposite.frag.metal</LogicalName>
      </EmbeddedResource>
    </ItemGroup>

</Project>
