<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-android;net10.0-ios</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="ppy.SDL3-CS" Version="2026.722.0"/>
        <PackageReference Include="ppy.SDL3_image-CS" Version="2026.722.0"/>
        <PackageReference Include="ppy.SDL3_mixer-CS" Version="2026.722.0"/>
        <PackageReference Include="SkiaSharp" Version="3.119.1"/>
        <PackageReference Include="NVorbis" Version="0.10.5" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Framework\" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Effects\Blur.frag.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Effects\Crt.frag.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Effects\Crt.vert.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Effects\FullscreenQuad.vert.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Effects\GlowComposite.frag.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Pipelines\Color.frag.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Pipelines\Color.vert.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Pipelines\ColorLight.frag.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Pipelines\ColorLight.vert.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Pipelines\Texture.frag.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Pipelines\Texture.vert.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Pipelines\TextureLight.frag.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Pipelines\TextureLight.vert.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Pipelines\TextureLightBump.frag.metal" />
      <EmbeddedResource Include="Framework.Backends\Sdl3Gpu\Assets\Shaders\Metal\Pipelines\TextureLightBump.vert.metal" />
    </ItemGroup>

</Project>
